port 26379
bind 0.0.0.0
protected-mode no
dir /tmp

sentinel resolve-hostnames yes
sentinel announce-hostnames yes
sentinel monitor demo-primary sentinel-primary 6379 2
sentinel down-after-milliseconds demo-primary 1500
sentinel failover-timeout demo-primary 10000
sentinel parallel-syncs demo-primary 1
